Add updated at and created at to index
meilisearch/meilisearch-dotnet pull request #170
Opened 2021-10-13 21:38 UTC by sander1095

This PR attempts to add the `UpdatedAt` and `CreatedAt` properties to the dotnet library.

Resolves #162

2021-10-13 21:40 UTC, sander1095 commented
You can see the unit tests fail.

Also, when I run the project locally when I get the following error when trying to create a new index:

```
Json deserialize error: unknown field `updatedAt`, expected `uid` or `primaryKey` at line 1 column 59,
```

I am kinda confused and stuck with this.

Any guidance would be appreciated.

2021-10-14 11:40 UTC, sander1095 commented
Carolina told me I could also ping

/cc @alallema

2021-10-14 13:01 UTC, alallema commented
> You can see the unit tests fail.
> 
> Also, when I run the project locally when I get the following error when trying to create a new index:
> 
> ```
> Json deserialize error: unknown field `updatedAt`, expected `uid` or `primaryKey` at line 1 column 59,
> ```
> 
> I am kinda confused and stuck with this, I thought the server would already be updated and ready for these properties?
> 
> Any guidance would be appreciated.
> 
> /cc @curquiza could you be of any assistance? I will also post this question in the Slack for help of other (community) members :)

Hi @sander1095,
I think the confusion came from these two fields `updateAt` and `createdAt` are generated by Meilisearch API, so you can `GET` them but the `Json deserialize error` means that you try to `POST` them to Meilisearch when you can't.
I let you check the [documentation](https://docs.meilisearch.com/reference/api/indexes.html#get-one-index) to see the difference between `get` and `create`.
The `updatedAt` and `createdAt` should be in the `Index` class but maybe not in the `Index` function depending on how the SDK is made.

2021-10-14 15:25 UTC, sander1095 commented
Thanks, that might just give me enough info to look further into this! Expect more updates this evening or perhaps this weekend

2021-10-14 18:03 UTC, sander1095 commented
Hello @alallema  ! I have been able to resolve the issue, thanks to your quick reply!

I am curious about your review! I know Carolina said you people are very busy, but I can't resist asking 🙈 !

Thanks for the opportunity to create this PR! It was fun! :)

2021-10-18 18:19 UTC, curquiza requested changes
Can you also updat `UpdateIndex()` in the Index class as you updated `FetchInfo()`? :) Thanks

2021-10-18 18:23 UTC, curquiza commented
bors try

2021-10-18 18:30 UTC, curquiza commented
looks like the tests do not pass anymore, small changes might be needed :)

2021-10-18 19:45 UTC, sander1095 commented
@curquiza I have made the requested changes 🥳

2021-10-18 19:58 UTC, sander1095 commented
I tried doing `bors try` but I don't have permission :)

2021-10-18 21:22 UTC, curquiza commented
bors try

2021-10-18 21:26 UTC, curquiza commented on src/Meilisearch/MeilisearchClient.cs
> +            var response = await this.http.PostAsJsonAsync("/indexes", index, options);
I think you should use `PostJsonCustomAsync`.
https://github.com/meilisearch/meilisearch-dotnet/blob/ad5ea3013528ca0b6a0ea59caba13af6de18b660/src/Meilisearch/Extensions/HttpExtensions.cs#L30-L44

2021-10-18 22:54 UTC, sander1095 commented on src/Meilisearch/MeilisearchClient.cs
> +            var response = await this.http.PostAsJsonAsync("/indexes", index, options);
Done.  Please check again.

Also note that I moved the `PropertyNamingPolicy = JsonNamingPolicy.CamelCase,` to inside the if block. I thought that if the user specifies different json serializer settings, we might not want to override their choices?

How do you see this?

2021-10-19 09:05 UTC, curquiza requested changes
Please don't modify `PrepareJsonPayload`, we don't want the `IgnoreNullValues` option be applied to every call :)

Also, it seems to have some git conflict you need to solve before I can review again!

thank you again for your involvement!

2021-10-19 11:55 UTC, curquiza commented on src/Meilisearch/MeilisearchClient.cs
> +
```suggestion
            var options = new JsonSerializerOptions { IgnoreNullValues = true };
```

2021-10-19 11:56 UTC, curquiza approved these changes
Thank you so much @sander1095 

bors merge

I think I already sent the form link, but just in case:
If you are participating in [Hacktoberfest](https://blog.meilisearch.com/contribute-hacktoberfest-2021/), and you would like to receive a small gift from MeiliSearch too, please complete [this form](https://meilisearch.typeform.com/to/rPexR5gq).

2021-10-19 12:17 UTC, curquiza commented
bors merge-

2021-10-19 12:17 UTC, curquiza commented
bors merge

2021-10-19 14:07 UTC, curquiza commented
Since bors seems to be broken I merge manually.

2021-10-19 14:07 UTC, merged