Add method to get the raw index information
meilisearch/meilisearch-dotnet pull request #173
Opened 2021-10-14 15:59 UTC by alejandrocq

PR for issue #163 

I have added the method `MeilisearchClient#getRawIndex` (which returns `JsonElement`, not sure if that fits your needs) and the test `MeilisearchClientTests#getRawIndex`. Let me know if it is ok :)

2021-10-14 16:23 UTC, curquiza requested changes
Can you put your test in IndexTests.cs? :)

2021-10-15 15:09 UTC, alejandrocq commented
@curquiza Sure! Let me get some time, and I will change it.

2021-10-18 18:13 UTC, curquiza requested changes
Your test is still in the `tests/Meilisearch.Tests/MeilisearchClientTests.cs` instead of `meilisearch-dotnet/tests/Meilisearch.Tests/IndexTests.cs`

2021-10-18 18:13 UTC, curquiza commented on src/Meilisearch/MeilisearchClient.cs
> +            var json = await (await this.http.GetAsync($"indexes/{uid}")).Content.ReadAsStringAsync();
`FetchInfo()` method in Index class already does this API call:

https://github.com/meilisearch/meilisearch-dotnet/blob/ad5ea3013528ca0b6a0ea59caba13af6de18b660/src/Meilisearch/Index.cs#L49

Can you change to avoid the code base having `await this.http.GetAsync($"indexes/{uid}")` twice?
For example, create a `GetRaw` method in `Index` class that would be used by `FetchInfo()` and `GetRawInfex()` :)

2021-10-18 19:19 UTC, alejandrocq commented on src/Meilisearch/MeilisearchClient.cs
> +            var json = await (await this.http.GetAsync($"indexes/{uid}")).Content.ReadAsStringAsync();
Sure! Good point. Working on it right now.

2021-10-18 19:42 UTC, alejandrocq commented on src/Meilisearch/MeilisearchClient.cs
> +            var json = await (await this.http.GetAsync($"indexes/{uid}")).Content.ReadAsStringAsync();
Done! Let me know your thoughts.

2021-10-18 21:30 UTC, curquiza commented on tests/Meilisearch.Tests/IndexTests.cs
> +            rawIndex.GetProperty("name").GetString().Should().Be("BasicIndex");
```suggestion
```

2021-10-18 21:31 UTC, curquiza approved these changes
Thanks @alejandrocq 

bors merge

If you are participating in [Hacktoberfest](https://blog.meilisearch.com/contribute-hacktoberfest-2021/), and you would like to receive a small gift from MeiliSearch too, please complete [this form](https://meilisearch.typeform.com/to/rPexR5gq).

2021-10-18 21:32 UTC, merged