Add method to fetch list of raw indexes
meilisearch/meilisearch-dotnet pull request #178
Opened 2021-10-17 08:51 UTC by Vivek-abstract

Related to issue:
https://github.com/meilisearch/meilisearch-dotnet/issues/155

Added a method GetAllRawIndexes which will return the response from the server as a enumerable of dictionary of key value pairs.
I didn't modify GetAllIndexes to use this new method because I think its best to keep it simple, adding conversion logic from dictionary to index would make it complicated. Let me know what you think

P.S. the 2 warnings would be fixed by the other PR https://github.com/meilisearch/meilisearch-dotnet/pull/172

2021-10-18 18:14 UTC, curquiza requested changes
I would not add a new dependency. Can we just make it work like this PR (https://github.com/meilisearch/meilisearch-dotnet/pull/173) suggests, without any new dependencies? :)

Thanks for your PR :)

2021-10-19 15:35 UTC, Vivek-abstract commented
@curquiza I changed it to use existing packages and return an ienumerable of JsonElements instead. 👍

2021-10-19 15:52 UTC, curquiza commented on src/Meilisearch/MeilisearchClient.cs
> +        /// Ex: [{"uid": "movies", "name":"movies", "createdAt":"2021-10-17T08:24:15.222102668Z",updatedAt:"2021-10-17T08:24:15.222102668Z",primaryKey:"movieId"}]. </returns>
```suggestion
        /// <returns>An IEnumerable of indexes in JsonElement format.</returns>
```

2021-10-19 15:52 UTC, curquiza approved these changes
Thank you again @Vivek-abstract 

bors merge

If you are participating in [Hacktoberfest](https://blog.meilisearch.com/contribute-hacktoberfest-2021/), and you would like to receive a small gift from MeiliSearch too, please complete [this form](https://meilisearch.typeform.com/to/rPexR5gq).

2021-10-19 15:54 UTC, merged