Remove dependancy on Microsoft.AspNetCore.WebUtilities
meilisearch/meilisearch-dotnet pull request #197
Opened 2021-11-23 11:45 UTC by juchom

# Pull Request

## What does this PR do?
Fixes #176 

This method is actually used in order to work with `QueryHelpers.AddQueryString`

```C#
public static IDictionary<string, string> AsDictionary(this object source, BindingFlags bindingAttr = BindingFlags.DeclaredOnly | BindingFlags.Public | BindingFlags.Instance)
{
    return source.GetType().GetProperties(bindingAttr).Where(p => p.GetValue(source, null) != null).ToDictionary(
        propInfo => char.ToLowerInvariant(propInfo.Name[0]) + propInfo.Name.Substring(1),
        propInfo => propInfo.GetValue(source, null).ToString());
}
```

I've created a new one that takes an object and transform it to a query string.

```C#
public static string ToQueryString(this object source, BindingFlags bindingAttr = BindingFlags.DeclaredOnly | BindingFlags.Public | BindingFlags.Instance)
{
    var values = source.GetType().GetProperties(bindingAttr)
    .Where(p => p.GetValue(source, null) != null)
    .Select(p =>
        Uri.EscapeDataString(char.ToLowerInvariant(p.Name[0]) + p.Name.Substring(1)) + "=" + Uri.EscapeDataString(p.GetValue(source, null).ToString()));
    var queryString = string.Join("&", values);
    return queryString;
}
```

I've change in `Index.cs`

```C#
// FROM
uri = QueryHelpers.AddQueryString(uri, new { primaryKey = primaryKey }.AsDictionary());
// TO
uri = $"{uri}?{new { primaryKey = primaryKey }.ToQueryString()}";
```

The query string is appended by hand, you may want to have a helper method to do this

Some tests have been added to make sure queries are the same.

2021-11-23 12:17 UTC, sander1095 commented
Resolves #176

2021-11-23 13:18 UTC, alallema commented
Hi @juchom,
Thank you so much for contributing to Meilisearch ❤️!
@curquiza is on holiday and will review your PR once they are back.

2021-11-23 17:19 UTC, juchom commented
I've runned some benchmarks also

```C#
[MemoryDiagnoser]
public class BenchmarkTest
{
	[Benchmark(Baseline = true)]
	[Arguments("/api/url", "key")]
	public string QueryAspNetCore(string uri, string primaryKey)
	{
		return QueryHelpers.AddQueryString(uri, new { primaryKey = primaryKey }.AsDictionary());
	}

	[Benchmark]
	[Arguments("/api/url", "key")]
	public string QueryCustom(string uri, string primaryKey)
	{
 		return $"{uri}?{new { primaryKey = primaryKey }.ToQueryString()}";
	}

	[Benchmark]  // Not used in project
	[Arguments("/api/url", "key")]
	public string QueryCustomSb(string uri, string primaryKey)
	{
		var sb = new StringBuilder();
		return sb.Append(uri).Append("?").Append(new { primaryKey = primaryKey }.ToQueryString()).ToString();
	}
}
```

```
|          Method |      uri | primaryKey |     Mean |    Error |   StdDev | Ratio | RatioSD |  Gen 0 | Allocated |
|---------------- |--------- |----------- |---------:|---------:|---------:|------:|--------:|-------:|----------:|
| QueryAspNetCore | /api/url |        key | 705.2 ns | 14.01 ns | 35.91 ns |  1.00 |    0.00 | 0.2928 |     920 B |
|     QueryCustom | /api/url |        key | 479.8 ns |  9.52 ns | 19.67 ns |  0.68 |    0.05 | 0.1760 |     552 B |
|   QueryCustomSb | /api/url |        key | 551.7 ns | 11.05 ns | 27.10 ns |  0.78 |    0.05 | 0.2422 |     760 B |
```

2021-11-24 07:45 UTC, sander1095 commented
I can't say anything about the quality of the benchmark, I don't have any experience with it. But if that is reliable, it looks good! Well done!

2021-12-09 15:44 UTC, curquiza requested changes

2021-12-09 15:44 UTC, curquiza commented on src/Meilisearch/ObjectExtensions.cs
> +        /// Transforms an MeiliSearch object into an url encoded query string.
```suggestion
        /// Transforms a MeiliSearch object into an URL encoded query string.
```

2021-12-09 15:45 UTC, curquiza approved these changes
Thanks @juchom for this quality PR and the explanation/details!

bors merge

2021-12-09 15:46 UTC, merged