Implement attributesToSearchOn
meilisearch/meilisearch-dotnet pull request #463
Opened 2023-08-08 20:13 UTC by SKeeneCode

# Pull Request

## Related issue
Fixes #457

## What does this PR do?
- Implements AttributesToSearchOn in SearchQuery

## PR checklist
Please check if your PR fulfills the following requirements:
- [ ] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [ ] Have you read the contributing guidelines?
- [ ] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

2023-08-08 20:26 UTC, brunoocasali requested changes
Just a typo in the code-samples and we are ready to go!

2023-08-08 20:26 UTC, brunoocasali commented on .code-samples.meilisearch.yaml
> +  await client.Index("movies").SearchAsync<Movie>("exciting", searchQuery);
```suggestion
  await client.Index("movies").SearchAsync<Movie>("adventure", searchQuery);
```

2023-08-08 20:41 UTC, SKeeneCode commented
Tests work locally but failed in the workflow with the following error:

```
Failed Meilisearch.Tests.ServerConfigs.BaseUriServer+SearchTests.CustomSearchWithAttributesToSearchOnNoResults [2 ms]
  Error Message:
   Meilisearch.MeilisearchApiError : MeilisearchApiError, Message: Unknown field `attributesToSearchOn`: expected one of `q`, `offset`, `limit`, `page`, `hitsPerPage`, `attributesToRetrieve`, `attributesToCrop`, `cropLength`, `attributesToHighlight`, `showMatchesPosition`, `filter`, `sort`, `facets`, `highlightPreTag`, `highlightPostTag`, `cropMarker`, `matchingStrategy`,
```

Locally with an instance set up with just:

```
curl -L https://install.meilisearch.com | sh
./meilisearch --master-key=masterKey
```

Tests pass in my IDE: 

![image](https://github.com/meilisearch/meilisearch-dotnet/assets/32420836/29e6998c-2f4a-47c9-a023-e0dcab315f05)

I notice the field `attributesToSearchOn` isn't included in the expect list in the error. Is the workflow spooling up an out of date version @brunoocasali ?

2023-08-09 04:55 UTC, ahmednfwela commented
@SKeeneCode you need to change this line to 1.3.0
https://github.com/meilisearch/meilisearch-dotnet/blob/main/.env#L1

@brunoocasali can we remove this from the .env file to grab the latest available meilisearch version ?

2023-08-09 07:40 UTC, SKeeneCode commented
@ahmednfwela thanks for pointing that out ^.^

2023-08-14 17:08 UTC, brunoocasali commented
Since v0.30 we have updated this version number, but I don't remember why. Let's change back to `latest` and if this is not what we expect, then we can go back to `v1.3.0` :D

2023-09-01 12:39 UTC, brunoocasali reviewed
Thanks a lot for your contribution!

bors merge

2023-09-01 12:39 UTC, brunoocasali approved these changes

2023-09-01 12:41 UTC, merged