Add support for text-separator customization
meilisearch/meilisearch-dotnet pull request #537
Opened 2024-05-21 10:53 UTC by Fronix

# Pull Request

## Related issue
Fixes #482

## What does this PR do?
- Adds support for the text-separator settings

## PR checklist
Please check if your PR fulfills the following requirements:
- [X] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [X] Have you read the contributing guidelines?
- [X] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

2024-05-21 14:20 UTC, ahmednfwela requested changes
Thanks for the PR

One change I would like to suggest, is that in general it's better to use `IEnumerable<...>` for function inputs and `List<...>` for function outputs

so for example:
```csharp
public async Task<List<string>> GetSeparatorTokensAsync(CancellationToken cancellationToken = default)
```
and
```csharp
public async Task<TaskInfo> UpdateNonSeparatorTokensAsync(IEnumerable<string> nonSeparatorTokens, CancellationToken cancellationToken = default)
```

2024-05-21 14:56 UTC, Fronix commented
> Thanks for the PR
> 
> One change I would like to suggest, is that in general it's better to use `IEnumerable<...>` for function inputs and `List<...>` for function outputs
> 
> so for example:
> 
> ```cs
> public async Task<List<string>> GetSeparatorTokensAsync(CancellationToken cancellationToken = default)
> ```
> 
> and
> 
> ```cs
> public async Task<TaskInfo> UpdateNonSeparatorTokensAsync(IEnumerable<string> nonSeparatorTokens, CancellationToken cancellationToken = default)
> ```

I agree 👍

2024-05-21 22:56 UTC, ahmednfwela approved these changes

2024-05-22 21:39 UTC, ahmednfwela commented
bors merge

2024-05-22 21:40 UTC, merged