Unknown Type Added
meilisearch/meilisearch-dotnet pull request #542
Opened 2024-06-27 04:23 UTC by postmeback

# Pull Request

## Related issue
Fixes #385 

## What does this PR do?
- Currently, it adds the "Unknown" type to the enum. It requires more tasks to do

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

2024-06-27 12:24 UTC, curquiza requested changes
As discussed, can you add tests? 😊

2024-06-27 12:41 UTC, postmeback commented
Yeah, I will. This PR will get updated soon.

2024-06-28 09:51 UTC, postmeback commented
> Yeah, I will. This PR will get updated soon.

I have updated this PR, to the best of my capabilities. Please review and provide feedback.

2024-07-02 18:05 UTC, postmeback commented
Seems like the build failed, Can you guide me on where to look?
@curquiza

2024-07-03 10:20 UTC, curquiza commented
@postmeback 
The tests [on `main` are green](https://github.com/meilisearch/meilisearch-dotnet/actions/runs/9776036741), so it's something you added that broke the CI.
Please, run the tests locally, you will have a better view of what is happening to fix them.

2024-07-04 18:38 UTC, postmeback commented
Well, I tried to run the tests, and below is the response.I have commented my tests.

![image](https://github.com/meilisearch/meilisearch-dotnet/assets/14862687/b917aac1-fb3b-46e1-a3d1-a8d54ec7dadf)

It seems I am restricted. Any idea on how to get past it ?

2024-07-06 15:55 UTC, curquiza commented
@postmeback there is not need for access to run the tests locally.
Did you follow the steps in [the CONTRIBUTING.md](https://github.com/meilisearch/meilisearch-dotnet/blob/main/CONTRIBUTING.md)?

2024-07-07 11:52 UTC, postmeback commented
I followed the steps and came up with below conclusion

`CreateUnknownTaskAsync` & `GetTaskWithUnknownTypeAsync` - this two methods have an URI, which I created and not added with API, that's the reason it is failing.

https://github.com/postmeback/meilisearch-dotnet/blob/c2934b51bae7b0f243009af109f26499cb7585a0/src/Meilisearch/MeilisearchClient.cs#L430

https://github.com/postmeback/meilisearch-dotnet/blob/c2934b51bae7b0f243009af109f26499cb7585a0/src/Meilisearch/MeilisearchClient.cs#L438C37-L438C64

Requesting you to have a look.

2024-07-08 12:49 UTC, curquiza commented
@postmeback `CreateUnknownTaskAsync` call a route that does not exist in Meilisearch. It cannot work.

Maybe @ahmednfwela can guide you on this, or @brunoocasali who opened the issue.

2024-07-09 08:07 UTC, ahmednfwela requested changes
to address the issue, we just need to configure the json serializer used by meilisearch to fallback to the unknown enum value

2024-07-09 08:07 UTC, ahmednfwela commented on src/Meilisearch/MeilisearchClient.cs
> +
all of these are unnecessary

2024-07-09 08:07 UTC, ahmednfwela commented on src/Meilisearch/QueryParameters/GetTaskQuery.cs
> +using System;
this new file is unnecessary

2024-07-09 08:07 UTC, ahmednfwela commented on src/Meilisearch/QueryParameters/UnknownTaskQuery.cs
> +using System;
this new file is unnecessary

2024-07-11 05:49 UTC, postmeback commented
I have removed the unnecessary files and methods from this PR. 

Also, if you can point to the `json serializer` file/function, which needs to be updated, that would greatly assist. @ahmednfwela

2024-07-11 06:17 UTC, ahmednfwela commented
@postmeback we use the default one https://learn.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonstringenumconverter?view=net-8.0

if this converter doesn't have a fallback option, we can create a custom one that inherits it

2024-07-11 06:35 UTC, ahmednfwela commented
check this [SO question](https://stackoverflow.com/questions/76709269/system-text-json-jsonstringenumconverter-with-custom-fallback-in-case-of-deseria) for similar solutions

2024-07-16 18:06 UTC, postmeback commented
Sure, thanks for the suggestion. I will update you soon.

2024-07-30 17:46 UTC, postmeback commented
![image](https://github.com/user-attachments/assets/e919ef21-19b6-498b-b493-4c097cd45dcc)


With the latest changes and all tests passing

2024-08-01 18:14 UTC, postmeback commented
![image](https://github.com/user-attachments/assets/728ad99d-471e-467b-9172-0f004a21af42)


I ran the formatter as well.

2024-08-02 17:05 UTC, ahmednfwela requested changes
can you please replace the json converter annotation on top of the enum with the new converter

2024-08-03 11:02 UTC, postmeback commented
Done.

2024-08-03 16:30 UTC, ahmednfwela approved these changes

2024-08-03 16:32 UTC, ahmednfwela commented
bors merge

2024-08-05 07:57 UTC, curquiza approved these changes
missing my approval

bors merge

2024-08-05 07:59 UTC, merged