Add rank threshold
meilisearch/meilisearch-dotnet pull request #582
Opened 2024-11-13 15:19 UTC by danFbach

# Pull Request

## Related issue
Fixes #544 

## What does this PR do?
- adds support for utilizing `RankingScoreThreshold` `SearchQuery` parameter.

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

2024-11-13 15:24 UTC, danFbach commented
Is it necessary to enforce the threshold range of `0.0 - 1.0` locally, or can we just allow meilisearch to ignore/reject when the value falls outside that range?

2024-11-27 10:18 UTC, curquiza commented on .code-samples.meilisearch.yaml
> +
```suggestion
```

2024-11-27 10:18 UTC, curquiza commented on .code-samples.meilisearch.yaml
> +  await client.Index("INDEX_NAME").SearchAsync<T>("badman", params);
```suggestion
  await client.Index("INDEX_NAME").SearchAsync<T>("badman", params);
```

2024-11-27 10:22 UTC, curquiza requested changes

2024-11-27 10:22 UTC, curquiza commented on .code-samples.meilisearch.yaml
> +    RankingScoreThreshold = 0.2M
why 0.2M? and not `0.2`, cf https://github.com/meilisearch/documentation/blob/04f26a35771305378ed0a506f4d60ef06d07bd7e/.code-samples.meilisearch.yaml#L1350

2024-11-27 10:22 UTC, curquiza commented on .code-samples.meilisearch.yaml
> +  await client.Index("INDEX_NAME").SearchAsync<T>("badman", params);
Can you remove the "no new line" at the end of the line?

2024-11-27 10:22 UTC, curquiza commented on .code-samples.meilisearch.yaml
> +  await client.Index("INDEX_NAME").SearchAsync<T>("badman", params);
we follow the editorconfig rules

2024-11-27 10:23 UTC, curquiza commented
@danFbach 

Looks like there is an issue with the lining (cf CI)

Can you fix this test?

2024-11-27 16:01 UTC, danFbach commented on .code-samples.meilisearch.yaml
> +    RankingScoreThreshold = 0.2M
c# requires `M` when setting a decimal value. `0.2` is interpreted as a `double` and `0.2M` is a `decimal`.
ex: 
![image](https://github.com/user-attachments/assets/f0f31d0b-35ea-4910-b5bd-682f24a9ad39)

2024-11-27 16:25 UTC, curquiza approved these changes
Awesome!

thank you

bors merge

2024-11-27 16:27 UTC, merged